---
    apiVersion: v1
    kind: ConfigMap
    metadata: 
        name: northwind-configmap
        labels:
            name: northwind-configmap
    data:
        DB_USER: root
        DB_HOST: mydb-svc

---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: northwind-app2-deploy
        labels:
            name: northwind-app
            version: "v2"
    spec:
        replicas: 1
        selector:
            matchLabels:
                name: myapp-pod
                version: "v2"
        template:
            metadata:
                name: myapp-pod
                labels:
                    name: myapp-pod
                    version: "v2"
            spec:
                containers:
                    - name: northwind-app-container
                      image: stackupiss/northwind-app:v2
                      imagePullPolicy: Always
                      env:
                        - name: DB_PASSWORD
                          valueFrom:
                            secretKeyRef:
                                name: northwind-db-secret
                                key: MYSQL_ROOT_PASSWORD
                        - name: INSTANCE_IP_ADDRESS
                          valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      envFrom:
                        - configMapRef:
                            name: northwind-configmap
                      ports:
                        - name: nw-app-http
                          containerPort: 3000